# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import functools
from calcEngine import BasicEngine


class Ui_calc(object):
    def setupUi(self, calc):
        self.str = ""
        calc.setObjectName("calc")
        calc.resize(674, 612)
        self.verticalLayoutWidget = QtWidgets.QWidget(calc)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 671, 601))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(
            QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint
        )
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum
        )
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(10)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 106))
        self.label.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(48)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(
            QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Maximum
        )
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Script")
        font.setPointSize(17)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_5 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 1, 1, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout.addWidget(self.pushButton_11, 3, 1, 1, 1)
        self.pushButton_12 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout.addWidget(self.pushButton_12, 3, 2, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout.addWidget(self.pushButton_7, 0, 2, 1, 1)
        self.pushButton_14 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout.addWidget(self.pushButton_14, 4, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 0, 0, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout.addWidget(self.pushButton_9, 2, 2, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout.addWidget(self.pushButton_15, 4, 2, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout.addWidget(self.pushButton_13, 4, 0, 1, 1)
        self.pushButton_10 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout.addWidget(self.pushButton_10, 3, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout.addWidget(self.pushButton_6, 2, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout.addWidget(self.pushButton_2, 1, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout.addWidget(self.pushButton_3, 2, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 0, 1, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout.addWidget(self.pushButton_8, 1, 2, 1, 1)
        self.pushButton_16 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout.addWidget(self.pushButton_16, 5, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(calc)
        self.pushButton.pressed.connect(functools.partial(self.addNumber, 1))  # type: ignore
        self.pushButton_4.pressed.connect(functools.partial(self.addNumber, 2))  # type: ignore
        self.pushButton_7.pressed.connect(functools.partial(self.addNumber, 3))  # type: ignore
        self.pushButton_2.pressed.connect(functools.partial(self.addNumber, 4))  # type: ignore
        self.pushButton_5.pressed.connect(functools.partial(self.addNumber, 5))  # type: ignore
        self.pushButton_8.pressed.connect(functools.partial(self.addNumber, 6))  # type: ignore
        self.pushButton_3.pressed.connect(functools.partial(self.addNumber, 7))  # type: ignore
        self.pushButton_6.pressed.connect(functools.partial(self.addNumber, 8))  # type: ignore
        self.pushButton_9.pressed.connect(functools.partial(self.addNumber, 9))  # type: ignore
        self.pushButton_10.released.connect(functools.partial(self.addNumber, 0))  # type: ignore
        self.pushButton_11.pressed.connect(functools.partial(self.addNumber, "+"))  # type: ignore
        self.pushButton_12.pressed.connect(functools.partial(self.addNumber, "-"))  # type: ignore
        self.pushButton_13.pressed.connect(functools.partial(self.addNumber, "*"))  # type: ignore
        self.pushButton_14.pressed.connect(functools.partial(self.addNumber, "/"))  # type: ignore
        self.pushButton_15.pressed.connect(self.evaluate)  # type: ignore
        self.pushButton_16.pressed.connect(self.clear_edit)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(calc)

    def set_engine(self, engine):
        self.engine = engine

    def evaluate(self):
        self.str = self.engine.evaluate(self.str)
        self.update_line()

    def clear_edit(self):
        self.str = ""
        self.update_line()

    def addNumber(self, number):
        self.str += str(number)
        self.update_line()

    def update_line(self):
        self.lineEdit.setText(self.str)

    def retranslateUi(self, calc):
        _translate = QtCore.QCoreApplication.translate
        calc.setWindowTitle(_translate("calc", "Form"))
        self.label.setText(_translate("calc", "CALCULATOR"))
        self.pushButton_5.setText(_translate("calc", "5"))
        self.pushButton_11.setText(_translate("calc", "+"))
        self.pushButton_12.setText(_translate("calc", "-"))
        self.pushButton_7.setText(_translate("calc", "3"))
        self.pushButton_14.setText(_translate("calc", "/"))
        self.pushButton.setText(_translate("calc", "1"))
        self.pushButton_9.setText(_translate("calc", "9"))
        self.pushButton_15.setText(_translate("calc", "="))
        self.pushButton_13.setText(_translate("calc", "*"))
        self.pushButton_10.setText(_translate("calc", "0"))
        self.pushButton_6.setText(_translate("calc", "8"))
        self.pushButton_2.setText(_translate("calc", "4"))
        self.pushButton_3.setText(_translate("calc", "7"))
        self.pushButton_4.setText(_translate("calc", "2"))
        self.pushButton_8.setText(_translate("calc", "6"))
        self.pushButton_16.setText(_translate("calc", "C"))


class MainWindow(QtWidgets.QWidget):
    def __init__(self, *args, obj=None, **kwargs):
        super(MainWindow, self).__init__(*args, **kwargs)
        self.ui = Ui_calc()
        engine = BasicEngine()
        self.ui.set_engine(engine)
        self.ui.setupUi(self)



